### ISSUE TITLE
Match up code design

### ISSUE THREAD

**Issue by ghost** [rom-py/rompy-legacy#12]
I have completed the first version of the match up code (see gist [here](https://gist.github.com/chriswhitwell/19a19c6ec7782a84f52fcbf454a20a8c)) and here are some of the decisions I made around the output format.

From what I could see there were 2 viable dataset formats for the matchup code.

1.  Create a 1D dimension that tracks the ID of each observation platform (i.e. each waverider buoy has a corresponding index). And then reference everything to this index. So in the case of the waveriders, lat,lon, time, model outputs and field observations can all be indexed by each waverider. The challenge is that the measurements dont share timestamps between different instruments, so we need to create a new time and model/measurement outputs for each platform. For small datasets this is no problem but I will get out of hand as the number of measurements you have increases.

2. Create universal timestamp, lat and lon dimensions. This is useful for using xarrays .sel method for slicing the matchup output but adds a bit of complexity when slicing the output models to match up against the field observations. By using universal lat/lon/time dimensions, the field obs outputs pad out the arrays with nans to match the array shape so I also saved another variable which contains the lat/lon indices which contain field observations. I think this could be bypassed with the .where method by the end user but will need to investigate it.

I ended up going with the latter because it will scale better with other field observations sources.
For the matchup code to work on observations with time-varying locations it will need some adjusting, probably just query the KDtree inside the time loop and change the how the lat/lon dims are created.

**Comment by pbranson** [comment]
Sorry only just saw this issue - thought it was all happening in the PR.

I think once you consider the moving platform case you will need to revert to 1. with the wavebuoys just being a special case of the moving platform code. Adding a variable for 'platform' makes sense, and repeated times also make sense. Ultimately we are converting to a 1D dataset of 'matchups' with several variables (time, grid references, obs, models values...)

**Comment by ghost** [comment]
Apologies, I hadn't figured out PR's at that time so I thought Id write out a blurb about some of the code design decisions I had made in the meantime. If there is a easy way to loop through the systematically, we could use netcdf groups to split up platforms to keep the dataset clean? I dont think xarray supports getting the keys of grouped nc's so would need to use netCDF4 probably

**Comment by ghost** [comment]
Just threw together some a test for the match up code, should I put the function in the "test_intake.py" file or start a new test file? If there are other utils that may be useful we could throw together a 'test_utils.py' file or similar

**Comment by pbranson** [comment]
Thanks Chris,

Yeah start a new module file called test_util.py
