### ISSUE TITLE
Schism Winds Sflux Generation Produces Misinterpreted Netcdf

### ISSUE THREAD

**Issue by benjaminleighton** [rom-py/rompy-legacy#125]
During generation of Wind data from SCHISMDataSflux and SfluxAir netcdf files have   scale_factor and add_offset encoding attributes on data variables and some data variables are of types other than float 64. Schism requires data to be written out without scale_factors and add_offset with data values representing the values that would otherwise be applied with those offsets. For example to posthoc fix this we

```
#open bad dataset
dsb = xr.open_dataset('./sflux_bad/air_1.0001.nc', chunks='auto')

# Loop through all variables in the dataset
for var in dsb.data_vars:
    # If the variable has scale_factor or add_offset attributes, remove them
    if 'scale_factor' in dsb[var].encoding:
        del dsb[var].encoding['scale_factor']
    if 'add_offset' in dsb[var].encoding:
        del dsb[var].encoding['add_offset']
    # set the data variable encoding to Float64
    dsb[var].encoding['dtype'] = np.dtypes.Float64DType()
 ```

**Comment by hot007** [comment]
Silly question, the above code appears to delete the scale and offset metadata but does not appear to apply the values to the data itself?

**Comment by benjaminleighton** [comment]
I think, but it needs testing, that xr.open_dataset does do this, it applies the values such that if you perform these steps then write back out the data you will get the adjusted values on disk. Thanks @hot007 for a prompt to go and test this some more. I will report back here.

**Comment by benjaminleighton** [comment]
I've checked and dsb = xr.open_dataset('./sflux_bad/air_1.0001.nc', chunks='auto') applies the scale and offset. Thus the after removing the scale and offset attributes and resaving it it will still have the scaled and offsetted values but now in a schism compatible format without the attributes. 

I've tested this like

```
#opens data and applies scale and offset
ds_schism_incompatible = xr.open_dataset(./sflux_bad/air_1.0001.nc', chunks='auto')
ds_schism_incompatible_test_value = ds_schism_incompatible['psl'].isel(time=0, ny_grid=100, nx_grid=100).values
# Loop through all variables in the dataset and remove scale and offset attributes
for var in ds_schism_incompatible.data_vars:
    # If the variable has scale_factor or add_offset attributes, remove them
    if 'scale_factor' in ds_schism_incompatible[var].encoding:
        del ds_schism_incompatible[var].encoding['scale_factor']
    if 'add_offset' in ds_schism_incompatible[var].encoding:
        del ds_schism_incompatible[var].encoding['add_offset']
    # set the data variable encoding to Float64
    ds_schism_incompatible[var].encoding['dtype'] = np.dtypes.Float64DType()

#save scaled and offset values but without attributes
ds_schism_incompatible.to_netcdf('test_fixed_good.nc')

#get a test value from the fixed dataset
ds_schism_compatible = xr.open_dataset('test_fixed_good.nc')
ds_fixed_test_value = ds_schism_compatible['psl'].isel(time=0, ny_grid=100, nx_grid=100).values

assert(ds_fixed_test_value == ds_schism_incompatible_test_value)
```

**Comment by benjaminleighton** [comment]
opening the data with netCDF4 Dataset using set_auto_scale(True) (or not) also confirms that scaled the scaled values of ds_fixed_test_value and ds_schism_incompatible_test_value are correct.

**Comment by hot007** [comment]
Thanks for confirming, that's good.

**Comment by tomdurrant** [comment]
This is fixed for sflux files.

winds old:
![schism_plot_wind_speed_0](https://github.com/user-attachments/assets/6e3cc7f3-e44d-4ed8-b18c-42cdd23547b0)

winds new:
![schism_plot_wind_speed_0](https://github.com/user-attachments/assets/db0627d8-b375-467b-8716-c88f4575b65a)

However waves still look suspect:
![schism_plot_WWM_18_0](https://github.com/user-attachments/assets/6bead78d-901d-4402-9f2c-718b03d8be4b)

So probably need to remove all packing for all datasources...?

**Comment by tomdurrant** [comment]
This was all fixed and should be working now
