### ISSUE TITLE
Having trouble getting SAR and Altimetry data for Perth model

### ISSUE THREAD

**Issue by ghost** [rom-py/rompy-legacy#15]
I am having a bit of trouble testing #13  for NRT SAR and Altimetry because I cant seem to get the intake driver to return for data for either of these sources for the spatial and temporal extents of the SWAN Perth Fc model runs currently available.

For the altimetry data, I can get results in the Perth domain up until 2020-10. The SAR data seems much more sparse.

@pbranson I was using this code from your notebook:

 `x = model_ds.longitude.values.flatten().tolist()
y = model_ds.latitude.values.flatten().tolist()
points = MultiPoint(list(map(Point,zip(x,y))))
geom = points.convex_hull.buffer(0.5).simplify(tolerance=0.01)`

to generate the geometry for the catalogue. Is a point buffer of 0.5 (degrees Im guessing?) too small for these datasets? Or is the nature of these sources such that they only measure in the Perth domain very rarely?

**Comment by pbranson** [comment]
Good pickup Chris. Note that you need to meshgrid the coordinates of the grid:

```
from shapely.geometry import MultiPoint, Point
import numpy as np
x = model_ds.longitude.values
y = model_ds.latitude.values 
xx,yy = np.meshgrid(x,y)
points = MultiPoint(list(map(Point,zip(xx.ravel(),yy.ravel())))) 
geom = points.convex_hull.buffer(0.01).simplify(tolerance=0.01)
geom
```
But there is only data from March 2020 within the model domain for SAR, and in Dec 2020 for Altimetry. I am backfilling a few runs from December, but March is before BOM changes models to APS3 so I would need to adjust. 

Lets forget about SAR validation for the time being.

@blasee @hot007

**Comment by pbranson** [comment]
OK I have backfilled this period for the altimetry: 2020-12-20 -> 2020-12-25
And currently backfilling for SAR, but you are right the coverage is infrequent:
```
<xarray.DataArray 'TIME' (TIME: 12)>
array(['2019-12-22T10:59:16.000010752', '2019-12-22T10:59:16.000010752',
       '2019-12-22T10:59:16.000010752', '2019-12-22T10:59:16.000010752',
       '2020-01-15T10:59:15.000016128', '2020-01-15T10:59:15.000016128',
       '2020-01-15T10:59:15.000016128', '2020-01-15T10:59:15.000016128',
       '2020-02-08T10:59:15.000016128', '2020-03-03T10:59:13.999981312',
       '2020-03-03T10:59:13.999981312', '2020-03-03T10:59:13.999981312'],
      dtype='datetime64[ns]')
```

**Comment by ghost** [comment]
Great! Will get to it this afternoon. @blasee I will send through a similar notebook to what I sent on Friday night for waveriders but now for altimetry so you can generate figures.

**Comment by pbranson** [comment]
This has been resolved by backfilling model to cover available data
