### ISSUE TITLE
nested intake catalogs

### ISSUE THREAD

**Issue by tomdurrant** [rom-py/rompy-legacy#29]
Issue 4 from June workshop. Comment was

Nested intake catalogs not supported e.g 
ds_intake_wind = rompy.core.data.DatasetIntake(catalog_uri='../../nglp_catalog/main.yaml', dataset_id='atoms.access_bom', kwargs=intake_kwargs)

**Comment by tomdurrant** [comment]
Comment from RG:

Nested catalogs should be supported that way, I have just tested on nested catalogs from oceanum using the redesigned class (SourceIntake). Please provide some reproduceable example and I can have a closer look

@pbranson can you provide an example catalog please?

**Comment by pbranson** [comment]
Would this catalog be sufficient? https://github.com/rom-py/rompy/blob/main/rompy/catalogs/master.yaml

**Comment by rafa-guedes** [comment]
@pbranson  I tried it with the two different datasources below from that nested catalog and it worked ok (actually the csiro example one didn't because pydap wasn't installed but once it was installed it worked ok). Do you have an specific example that isn't working?

```
from rompy.core.data import SourceIntake


source = SourceIntake(
    catalog_uri="/source/csiro/rompy/rompy/catalogs/master.yaml",
    dataset_id="oceanum.era5_wind10m"
)

source.open()
```

```
source = SourceIntake(
    catalog_uri="/source/csiro/rompy/rompy/catalogs/master.yaml",
    dataset_id="csiro.swan.swan_perth_fc.map"
)

source.open()
```

**Comment by pbranson** [comment]
No if those are working then I think this can be closed

**Comment by rafa-guedes** [comment]
Ok closing it then!
