### ISSUE TITLE
Generate additional gr3 files on the fly

### ISSUE THREAD

**Issue by tomdurrant** [rom-py/rompy-legacy#54]
At the moment, the grid object required supply of a number of gr3 files along with the grid definition file. Often these are just constant values, and consist of of a text file containing node numbers and constant values. In this case, it would be preferable to generate these on the fly rather than having to pass these around. Vanessa supplied a perl script to do this. 

[gen_gr3.txt](https://github.com/rom-py/rompy/files/13469922/gen_gr3.txt)

This should be incorporated into the wrapper

**Comment by VHernaman** [comment]
to be pedantic regarding the above, 
... consist of of a text file containing node numbers, COORDS and constant values.

**Comment by tomdurrant** [comment]
This was fixed with merge of #58
