### ISSUE TITLE
remove dependency on Np1DArray, Np2DArray 

### ISSUE THREAD

**Issue by tomdurrant** [rom-py/rompy-legacy#84]
These objects allow representations of numpy arrays as pydantic objects. They are the input type for the basegrid object. 

We need x and y attributes for that base object for a lot of the logic to work. However, none of the downstream objects require these as inputs. Having them as first class pydantic attributes means that any serialised object includes these as yaml representations of numpy arrays which is really ugly. I suggest we remove these as inputs, and just make them an abstract property instead. 

I'll have a play with it and propose something

**Comment by benjaminleighton** [comment]
Ben to check with SImon on numpy 2 requirements
