### ISSUE TITLE
Better document rompy SCHISM 

### ISSUE THREAD

**Issue by benjaminleighton** [rom-py/rompy-legacy#86]
Users are reporting that "for wind, ocean, wave and tides forcings, we have SCHISMDataSflux, SCHISMDataOcean, SCHISMDataWave, SCHISMDataTides" and also "SCHISMDataBoundary" but it is unclear what the differences are between these. @Ckirezci

**Comment by tomdurrant** [comment]
Sounds like this was primarily due to a lack of knowledge of the existence of the docs. Closing for now, feel free to open again if need
