### ISSUE TITLE
GR3Generator incompatible with base class

### ISSUE THREAD

**Issue by benjaminleighton** [rom-py/rompy-legacy#87]
----> 1 GR3Generator(grid_location / "hgrid.gr3", 'diffmin', 1)

TypeError: BaseModel.__init__() takes 1 positional argument but 4 were given

**Comment by tomdurrant** [comment]
Pydantic doesn't support positional arguments (e.g. here for reasons https://github.com/pydantic/pydantic/issues/116)

You have to instantiate using named args

```
In [7]: GR3Generator(hgrid="test_data/hgrid.gr3", gr3_type='diffmin', value=1)
Out[7]: GR3Generator(hgrid=PosixPath('test_data/hgrid.gr3'), gr3_type='diffmin', value=1.0, crs='epsg:4326')
```
