### ISSUE TITLE
Import issues for Numpy version <2

### ISSUE THREAD

**Issue by blasee** [rom-py/rompy-legacy#97]
Hey team,

We run a few environments where we have pinned Numpy version <2 (for now) and we're getting import errors for the latest development version of Rompy. Is it possible for Rompy to allow for environments running Numpy version less than 2?

```bash
python3.10 -m venv temp_env
source temp_env/bin/activate
pip install rompy
pip install "numpy<2"
pip freeze
```

[pip_freeze.txt](https://github.com/user-attachments/files/16369100/pip_freeze.txt)

```python
import rompy.swan
```

[traceback.txt](https://github.com/user-attachments/files/16369174/traceback.txt)

The issue arises due to the latest release of `pydantic_numpy` (6.0.0), [which requires `numpy>=2.0.0`](https://github.com/caniko/pydantic-numpy/blob/trunk/pyproject.toml).

Keep up the great work!

**Comment by rafa-guedes** [comment]
@blasee I can replicate your problem. If you set `numpy<2` inside pyproject.toml, the compatible versions are correctly installed:

numpy==1.26.4
pydantic_numpy==5.0.2

However it is probably better those aren't pinned in rompy itself if we can avoid it. The easiest solution is installing `numpy<2` and also `pydantic_numpy<6` after you have installed rompy, I have tested it here and it works okay.

**Comment by blasee** [comment]
Thanks @rafa-guedes. Pinning `pydantic_numpy` to less than 6 solves this issue.
